name: Run scraper daily

on:
  schedule:
    - cron: '0 2 * * *'  # 한국 시간 오전 11시 (UTC+9)
  workflow_dispatch: # 수동 실행도 가능

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY }}
        run: node index.js
